// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace HRDemoAPI.DataCore.Models;

public enum AttendanceStatus : short
{
    Present = 0,
    Absent = 1,
    Late = 2
}
public partial class Attendance
{
    public int AttendanceID { get; set; }

    public DateTimeOffset Date { get; set; }

    public DateTimeOffset CheckInTime { get; set; }

    public DateTimeOffset CheckOutTime { get; set; }

    public AttendanceStatus Status { get; set; }

    public int? EmployeeID { get; set; }

    public virtual Employee Employee { get; set; }
}