// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace HRDemoAPI.DataCore.Models;

public partial class Department
{
    public int DepartmentID { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int? ManagerID { get; set; }

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    public virtual Employee Manager { get; set; }
}