// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;

namespace HRDemoAPI.DataCore.Models;

public enum EmployeeStatus : short
{
    Pending = 0,
    Active = 1,
    Terminated = 2
}

[Owned]
public partial class EmployeeAddress
{
    public string Line1 { get; set; }
    public string Line2 { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public string PostalCode { get; set; }
    public string Country { get; set; }
}

public partial class Employee
{
    public int EmployeeID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string JobTitle { get; set; }

    public DateTimeOffset DateOfHire { get; set; }

    public EmployeeStatus Status { get; set; }

    public EmployeeAddress Address { get; set; }

    public int? DepartmentID { get; set; }

    public double Salary { get; set; }

    public virtual ICollection<Attendance> Attendances { get; set; } = new List<Attendance>();

    public virtual Department Department { get; set; }

    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();

    public virtual ICollection<Leave> Leaves { get; set; } = new List<Leave>();

    public virtual ICollection<Payroll> Payrolls { get; set; } = new List<Payroll>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}