// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace HRDemoAPI.DataCore.Models
{
    public partial interface IHRDemoApiContextProcedures
    {
        Task<List<GetEmployeeMonthlyReportResult>> GetEmployeeMonthlyReportAsync(int? employeeId, int? year, int? month, double? offset, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
