// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace HRDemoAPI.DataCore.Models;
public enum LeaveStatus : short
{
    Pending = 0,
    Approved = 1,
    Rejected = 2
}

public enum LeaveType : short
{
    Sick = 0,
    Casual = 1,
    Parental = 2,
    Bereavement = 3,
    Unpaid = 4
}
public partial class Leave
{
    public int LeaveID { get; set; }

    public LeaveType Type { get; set; }

    public DateTimeOffset StartDate { get; set; }

    public DateTimeOffset EndDate { get; set; }

    public string Reason { get; set; }

    public LeaveStatus Status { get; set; }

    public int? EmployeeID { get; set; }

    public virtual Employee Employee { get; set; }
}