// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;

namespace HRDemoAPI.DataCore.Models;
public enum PayrollStatus : short
{
    Pending = 0,
    Processed = 1,
    Failed = 2
}

[Owned]
public partial class EmployeeSalary
{
    public double GrossAmount { get; set; }
    public double PreTaxDeduction { get; set; }
    public double TaxDeduction { get; set; }
    public double PostTaxDeduction { get; set; }
    public double NetAmount { get; set; }
}
public partial class Payroll
{
    public int PayrollID { get; set; }

    public short Month { get; set; }

    public short Year { get; set; }
    public EmployeeSalary Salary { get; set; }

    public PayrollStatus Status { get; set; }

    public int? EmployeeID { get; set; }

    public virtual Employee Employee { get; set; }
}