// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace HRDemoAPI.DataCore.Models;

public enum UserRole : short
{
    User = 0,
    Admin = 1
}
public partial class User
{
    public int UserID { get; set; }

    public string Name { get; set; }

    public int? EmployeeID { get; set; }

    public UserRole Role { get; set; }

    public virtual Employee Employee { get; set; }
}