//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRDemoReportUI.Service.HRDemoReportService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportRequest", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ReportRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short MonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float TimezoneOffsetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Month {
            get {
                return this.MonthField;
            }
            set {
                if ((this.MonthField.Equals(value) != true)) {
                    this.MonthField = value;
                    this.RaisePropertyChanged("Month");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float TimezoneOffset {
            get {
                return this.TimezoneOffsetField;
            }
            set {
                if ((this.TimezoneOffsetField.Equals(value) != true)) {
                    this.TimezoneOffsetField = value;
                    this.RaisePropertyChanged("TimezoneOffset");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportResponse", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ReportResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HRDemoReportUI.Service.HRDemoReportService.EmployeeReport EmployeeReportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HRDemoReportUI.Service.HRDemoReportService.PayrollReport[] PayrollReportsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HRDemoReportUI.Service.HRDemoReportService.EmployeeReport EmployeeReport {
            get {
                return this.EmployeeReportField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeReportField, value) != true)) {
                    this.EmployeeReportField = value;
                    this.RaisePropertyChanged("EmployeeReport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HRDemoReportUI.Service.HRDemoReportService.PayrollReport[] PayrollReports {
            get {
                return this.PayrollReportsField;
            }
            set {
                if ((object.ReferenceEquals(this.PayrollReportsField, value) != true)) {
                    this.PayrollReportsField = value;
                    this.RaisePropertyChanged("PayrollReports");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeReport", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class EmployeeReport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AnnualSalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BereavementLeaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CasualLeaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LateDaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LeaveDaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MonthSalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentalLeaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PresentDaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SickLeaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UnpaidLeaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double WorkingDaysInMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double WorkingDaysInYearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AnnualSalary {
            get {
                return this.AnnualSalaryField;
            }
            set {
                if ((this.AnnualSalaryField.Equals(value) != true)) {
                    this.AnnualSalaryField = value;
                    this.RaisePropertyChanged("AnnualSalary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BereavementLeave {
            get {
                return this.BereavementLeaveField;
            }
            set {
                if ((this.BereavementLeaveField.Equals(value) != true)) {
                    this.BereavementLeaveField = value;
                    this.RaisePropertyChanged("BereavementLeave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CasualLeave {
            get {
                return this.CasualLeaveField;
            }
            set {
                if ((this.CasualLeaveField.Equals(value) != true)) {
                    this.CasualLeaveField = value;
                    this.RaisePropertyChanged("CasualLeave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LateDays {
            get {
                return this.LateDaysField;
            }
            set {
                if ((this.LateDaysField.Equals(value) != true)) {
                    this.LateDaysField = value;
                    this.RaisePropertyChanged("LateDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LeaveDays {
            get {
                return this.LeaveDaysField;
            }
            set {
                if ((this.LeaveDaysField.Equals(value) != true)) {
                    this.LeaveDaysField = value;
                    this.RaisePropertyChanged("LeaveDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MonthSalary {
            get {
                return this.MonthSalaryField;
            }
            set {
                if ((this.MonthSalaryField.Equals(value) != true)) {
                    this.MonthSalaryField = value;
                    this.RaisePropertyChanged("MonthSalary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentalLeave {
            get {
                return this.ParentalLeaveField;
            }
            set {
                if ((this.ParentalLeaveField.Equals(value) != true)) {
                    this.ParentalLeaveField = value;
                    this.RaisePropertyChanged("ParentalLeave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PresentDays {
            get {
                return this.PresentDaysField;
            }
            set {
                if ((this.PresentDaysField.Equals(value) != true)) {
                    this.PresentDaysField = value;
                    this.RaisePropertyChanged("PresentDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SickLeave {
            get {
                return this.SickLeaveField;
            }
            set {
                if ((this.SickLeaveField.Equals(value) != true)) {
                    this.SickLeaveField = value;
                    this.RaisePropertyChanged("SickLeave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UnpaidLeave {
            get {
                return this.UnpaidLeaveField;
            }
            set {
                if ((this.UnpaidLeaveField.Equals(value) != true)) {
                    this.UnpaidLeaveField = value;
                    this.RaisePropertyChanged("UnpaidLeave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double WorkingDaysInMonth {
            get {
                return this.WorkingDaysInMonthField;
            }
            set {
                if ((this.WorkingDaysInMonthField.Equals(value) != true)) {
                    this.WorkingDaysInMonthField = value;
                    this.RaisePropertyChanged("WorkingDaysInMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double WorkingDaysInYear {
            get {
                return this.WorkingDaysInYearField;
            }
            set {
                if ((this.WorkingDaysInYearField.Equals(value) != true)) {
                    this.WorkingDaysInYearField = value;
                    this.RaisePropertyChanged("WorkingDaysInYear");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PayrollReport", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class PayrollReport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double GrossAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short MonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double NetAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PayrollIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PostTaxDeductionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PreTaxDeductionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TaxDeductionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double GrossAmount {
            get {
                return this.GrossAmountField;
            }
            set {
                if ((this.GrossAmountField.Equals(value) != true)) {
                    this.GrossAmountField = value;
                    this.RaisePropertyChanged("GrossAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Month {
            get {
                return this.MonthField;
            }
            set {
                if ((this.MonthField.Equals(value) != true)) {
                    this.MonthField = value;
                    this.RaisePropertyChanged("Month");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double NetAmount {
            get {
                return this.NetAmountField;
            }
            set {
                if ((this.NetAmountField.Equals(value) != true)) {
                    this.NetAmountField = value;
                    this.RaisePropertyChanged("NetAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PayrollID {
            get {
                return this.PayrollIDField;
            }
            set {
                if ((this.PayrollIDField.Equals(value) != true)) {
                    this.PayrollIDField = value;
                    this.RaisePropertyChanged("PayrollID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PostTaxDeduction {
            get {
                return this.PostTaxDeductionField;
            }
            set {
                if ((this.PostTaxDeductionField.Equals(value) != true)) {
                    this.PostTaxDeductionField = value;
                    this.RaisePropertyChanged("PostTaxDeduction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PreTaxDeduction {
            get {
                return this.PreTaxDeductionField;
            }
            set {
                if ((this.PreTaxDeductionField.Equals(value) != true)) {
                    this.PreTaxDeductionField = value;
                    this.RaisePropertyChanged("PreTaxDeduction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TaxDeduction {
            get {
                return this.TaxDeductionField;
            }
            set {
                if ((this.TaxDeductionField.Equals(value) != true)) {
                    this.TaxDeductionField = value;
                    this.RaisePropertyChanged("TaxDeduction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRequest", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class UserRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeResponse", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRDemoReportUI.Service.HRDemoReportService.UserResponse))]
    public partial class EmployeeResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeName {
            get {
                return this.EmployeeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeNameField, value) != true)) {
                    this.EmployeeNameField = value;
                    this.RaisePropertyChanged("EmployeeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserResponse", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class UserResponse : HRDemoReportUI.Service.HRDemoReportService.EmployeeResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HRDemoReportUI.Service.HRDemoReportService.DepartmentResponse[] ManagedDepartmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short UserRoleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HRDemoReportUI.Service.HRDemoReportService.DepartmentResponse[] ManagedDepartments {
            get {
                return this.ManagedDepartmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ManagedDepartmentsField, value) != true)) {
                    this.ManagedDepartmentsField = value;
                    this.RaisePropertyChanged("ManagedDepartments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short UserRole {
            get {
                return this.UserRoleField;
            }
            set {
                if ((this.UserRoleField.Equals(value) != true)) {
                    this.UserRoleField = value;
                    this.RaisePropertyChanged("UserRole");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepartmentResponse", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class DepartmentResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DepartmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartmentID {
            get {
                return this.DepartmentIDField;
            }
            set {
                if ((this.DepartmentIDField.Equals(value) != true)) {
                    this.DepartmentIDField = value;
                    this.RaisePropertyChanged("DepartmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentName {
            get {
                return this.DepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNameField, value) != true)) {
                    this.DepartmentNameField = value;
                    this.RaisePropertyChanged("DepartmentName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeRequest", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class EmployeeRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] ManagedDepartmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SearchNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] ManagedDepartments {
            get {
                return this.ManagedDepartmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ManagedDepartmentsField, value) != true)) {
                    this.ManagedDepartmentsField = value;
                    this.RaisePropertyChanged("ManagedDepartments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SearchName {
            get {
                return this.SearchNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchNameField, value) != true)) {
                    this.SearchNameField = value;
                    this.RaisePropertyChanged("SearchName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HRDemoReportService.IHRDemoReportService")]
    public interface IHRDemoReportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHRDemoReportService/GetEmployeeMonthlyReport", ReplyAction="http://tempuri.org/IHRDemoReportService/GetEmployeeMonthlyReportResponse")]
        HRDemoReportUI.Service.HRDemoReportService.ReportResponse GetEmployeeMonthlyReport(HRDemoReportUI.Service.HRDemoReportService.ReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHRDemoReportService/GetEmployeeMonthlyReport", ReplyAction="http://tempuri.org/IHRDemoReportService/GetEmployeeMonthlyReportResponse")]
        System.Threading.Tasks.Task<HRDemoReportUI.Service.HRDemoReportService.ReportResponse> GetEmployeeMonthlyReportAsync(HRDemoReportUI.Service.HRDemoReportService.ReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHRDemoReportService/GetUserDetails", ReplyAction="http://tempuri.org/IHRDemoReportService/GetUserDetailsResponse")]
        HRDemoReportUI.Service.HRDemoReportService.UserResponse GetUserDetails(HRDemoReportUI.Service.HRDemoReportService.UserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHRDemoReportService/GetUserDetails", ReplyAction="http://tempuri.org/IHRDemoReportService/GetUserDetailsResponse")]
        System.Threading.Tasks.Task<HRDemoReportUI.Service.HRDemoReportService.UserResponse> GetUserDetailsAsync(HRDemoReportUI.Service.HRDemoReportService.UserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHRDemoReportService/GetEmployeeOptions", ReplyAction="http://tempuri.org/IHRDemoReportService/GetEmployeeOptionsResponse")]
        HRDemoReportUI.Service.HRDemoReportService.EmployeeResponse[] GetEmployeeOptions(HRDemoReportUI.Service.HRDemoReportService.EmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHRDemoReportService/GetEmployeeOptions", ReplyAction="http://tempuri.org/IHRDemoReportService/GetEmployeeOptionsResponse")]
        System.Threading.Tasks.Task<HRDemoReportUI.Service.HRDemoReportService.EmployeeResponse[]> GetEmployeeOptionsAsync(HRDemoReportUI.Service.HRDemoReportService.EmployeeRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHRDemoReportServiceChannel : HRDemoReportUI.Service.HRDemoReportService.IHRDemoReportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HRDemoReportServiceClient : System.ServiceModel.ClientBase<HRDemoReportUI.Service.HRDemoReportService.IHRDemoReportService>, HRDemoReportUI.Service.HRDemoReportService.IHRDemoReportService {
        
        public HRDemoReportServiceClient() {
        }
        
        public HRDemoReportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HRDemoReportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HRDemoReportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HRDemoReportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HRDemoReportUI.Service.HRDemoReportService.ReportResponse GetEmployeeMonthlyReport(HRDemoReportUI.Service.HRDemoReportService.ReportRequest request) {
            return base.Channel.GetEmployeeMonthlyReport(request);
        }
        
        public System.Threading.Tasks.Task<HRDemoReportUI.Service.HRDemoReportService.ReportResponse> GetEmployeeMonthlyReportAsync(HRDemoReportUI.Service.HRDemoReportService.ReportRequest request) {
            return base.Channel.GetEmployeeMonthlyReportAsync(request);
        }
        
        public HRDemoReportUI.Service.HRDemoReportService.UserResponse GetUserDetails(HRDemoReportUI.Service.HRDemoReportService.UserRequest request) {
            return base.Channel.GetUserDetails(request);
        }
        
        public System.Threading.Tasks.Task<HRDemoReportUI.Service.HRDemoReportService.UserResponse> GetUserDetailsAsync(HRDemoReportUI.Service.HRDemoReportService.UserRequest request) {
            return base.Channel.GetUserDetailsAsync(request);
        }
        
        public HRDemoReportUI.Service.HRDemoReportService.EmployeeResponse[] GetEmployeeOptions(HRDemoReportUI.Service.HRDemoReportService.EmployeeRequest request) {
            return base.Channel.GetEmployeeOptions(request);
        }
        
        public System.Threading.Tasks.Task<HRDemoReportUI.Service.HRDemoReportService.EmployeeResponse[]> GetEmployeeOptionsAsync(HRDemoReportUI.Service.HRDemoReportService.EmployeeRequest request) {
            return base.Channel.GetEmployeeOptionsAsync(request);
        }
    }
}
