//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRDemoReportService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportRequest", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class ReportRequest : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private int EmployeeIDField;
        
        private short MonthField;
        
        private float TimezoneOffsetField;
        
        private short YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeID
        {
            get
            {
                return this.EmployeeIDField;
            }
            set
            {
                if ((this.EmployeeIDField.Equals(value) != true))
                {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Month
        {
            get
            {
                return this.MonthField;
            }
            set
            {
                if ((this.MonthField.Equals(value) != true))
                {
                    this.MonthField = value;
                    this.RaisePropertyChanged("Month");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float TimezoneOffset
        {
            get
            {
                return this.TimezoneOffsetField;
            }
            set
            {
                if ((this.TimezoneOffsetField.Equals(value) != true))
                {
                    this.TimezoneOffsetField = value;
                    this.RaisePropertyChanged("TimezoneOffset");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Year
        {
            get
            {
                return this.YearField;
            }
            set
            {
                if ((this.YearField.Equals(value) != true))
                {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportResponse", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class ReportResponse : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private HRDemoReportService.EmployeeReport EmployeeReportField;
        
        private HRDemoReportService.PayrollReport[] PayrollReportsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HRDemoReportService.EmployeeReport EmployeeReport
        {
            get
            {
                return this.EmployeeReportField;
            }
            set
            {
                if ((object.ReferenceEquals(this.EmployeeReportField, value) != true))
                {
                    this.EmployeeReportField = value;
                    this.RaisePropertyChanged("EmployeeReport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HRDemoReportService.PayrollReport[] PayrollReports
        {
            get
            {
                return this.PayrollReportsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PayrollReportsField, value) != true))
                {
                    this.PayrollReportsField = value;
                    this.RaisePropertyChanged("PayrollReports");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeReport", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class EmployeeReport : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private int AbsentDaysField;
        
        private double AnnualSalaryField;
        
        private int BereavementLeaveField;
        
        private int CasualLeaveField;
        
        private string CountryField;
        
        private int EmployeeIDField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private int LateDaysField;
        
        private int LeaveDaysField;
        
        private double MonthSalaryField;
        
        private int ParentalLeaveField;
        
        private int PresentDaysField;
        
        private int SickLeaveField;
        
        private string StateField;
        
        private int UnpaidLeaveField;
        
        private short WorkingDaysInMonthField;
        
        private short WorkingDaysInYearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AbsentDays
        {
            get
            {
                return this.AbsentDaysField;
            }
            set
            {
                if ((this.AbsentDaysField.Equals(value) != true))
                {
                    this.AbsentDaysField = value;
                    this.RaisePropertyChanged("AbsentDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AnnualSalary
        {
            get
            {
                return this.AnnualSalaryField;
            }
            set
            {
                if ((this.AnnualSalaryField.Equals(value) != true))
                {
                    this.AnnualSalaryField = value;
                    this.RaisePropertyChanged("AnnualSalary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BereavementLeave
        {
            get
            {
                return this.BereavementLeaveField;
            }
            set
            {
                if ((this.BereavementLeaveField.Equals(value) != true))
                {
                    this.BereavementLeaveField = value;
                    this.RaisePropertyChanged("BereavementLeave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CasualLeave
        {
            get
            {
                return this.CasualLeaveField;
            }
            set
            {
                if ((this.CasualLeaveField.Equals(value) != true))
                {
                    this.CasualLeaveField = value;
                    this.RaisePropertyChanged("CasualLeave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CountryField, value) != true))
                {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeID
        {
            get
            {
                return this.EmployeeIDField;
            }
            set
            {
                if ((this.EmployeeIDField.Equals(value) != true))
                {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true))
                {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LastNameField, value) != true))
                {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LateDays
        {
            get
            {
                return this.LateDaysField;
            }
            set
            {
                if ((this.LateDaysField.Equals(value) != true))
                {
                    this.LateDaysField = value;
                    this.RaisePropertyChanged("LateDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LeaveDays
        {
            get
            {
                return this.LeaveDaysField;
            }
            set
            {
                if ((this.LeaveDaysField.Equals(value) != true))
                {
                    this.LeaveDaysField = value;
                    this.RaisePropertyChanged("LeaveDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MonthSalary
        {
            get
            {
                return this.MonthSalaryField;
            }
            set
            {
                if ((this.MonthSalaryField.Equals(value) != true))
                {
                    this.MonthSalaryField = value;
                    this.RaisePropertyChanged("MonthSalary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentalLeave
        {
            get
            {
                return this.ParentalLeaveField;
            }
            set
            {
                if ((this.ParentalLeaveField.Equals(value) != true))
                {
                    this.ParentalLeaveField = value;
                    this.RaisePropertyChanged("ParentalLeave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PresentDays
        {
            get
            {
                return this.PresentDaysField;
            }
            set
            {
                if ((this.PresentDaysField.Equals(value) != true))
                {
                    this.PresentDaysField = value;
                    this.RaisePropertyChanged("PresentDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SickLeave
        {
            get
            {
                return this.SickLeaveField;
            }
            set
            {
                if ((this.SickLeaveField.Equals(value) != true))
                {
                    this.SickLeaveField = value;
                    this.RaisePropertyChanged("SickLeave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                if ((object.ReferenceEquals(this.StateField, value) != true))
                {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UnpaidLeave
        {
            get
            {
                return this.UnpaidLeaveField;
            }
            set
            {
                if ((this.UnpaidLeaveField.Equals(value) != true))
                {
                    this.UnpaidLeaveField = value;
                    this.RaisePropertyChanged("UnpaidLeave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short WorkingDaysInMonth
        {
            get
            {
                return this.WorkingDaysInMonthField;
            }
            set
            {
                if ((this.WorkingDaysInMonthField.Equals(value) != true))
                {
                    this.WorkingDaysInMonthField = value;
                    this.RaisePropertyChanged("WorkingDaysInMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short WorkingDaysInYear
        {
            get
            {
                return this.WorkingDaysInYearField;
            }
            set
            {
                if ((this.WorkingDaysInYearField.Equals(value) != true))
                {
                    this.WorkingDaysInYearField = value;
                    this.RaisePropertyChanged("WorkingDaysInYear");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PayrollReport", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class PayrollReport : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private double GrossAmountField;
        
        private short MonthField;
        
        private double NetAmountField;
        
        private int PayrollIDField;
        
        private double PostTaxDeductionField;
        
        private double PreTaxDeductionField;
        
        private double TaxDeductionField;
        
        private short YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double GrossAmount
        {
            get
            {
                return this.GrossAmountField;
            }
            set
            {
                if ((this.GrossAmountField.Equals(value) != true))
                {
                    this.GrossAmountField = value;
                    this.RaisePropertyChanged("GrossAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Month
        {
            get
            {
                return this.MonthField;
            }
            set
            {
                if ((this.MonthField.Equals(value) != true))
                {
                    this.MonthField = value;
                    this.RaisePropertyChanged("Month");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double NetAmount
        {
            get
            {
                return this.NetAmountField;
            }
            set
            {
                if ((this.NetAmountField.Equals(value) != true))
                {
                    this.NetAmountField = value;
                    this.RaisePropertyChanged("NetAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PayrollID
        {
            get
            {
                return this.PayrollIDField;
            }
            set
            {
                if ((this.PayrollIDField.Equals(value) != true))
                {
                    this.PayrollIDField = value;
                    this.RaisePropertyChanged("PayrollID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PostTaxDeduction
        {
            get
            {
                return this.PostTaxDeductionField;
            }
            set
            {
                if ((this.PostTaxDeductionField.Equals(value) != true))
                {
                    this.PostTaxDeductionField = value;
                    this.RaisePropertyChanged("PostTaxDeduction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PreTaxDeduction
        {
            get
            {
                return this.PreTaxDeductionField;
            }
            set
            {
                if ((this.PreTaxDeductionField.Equals(value) != true))
                {
                    this.PreTaxDeductionField = value;
                    this.RaisePropertyChanged("PreTaxDeduction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TaxDeduction
        {
            get
            {
                return this.TaxDeductionField;
            }
            set
            {
                if ((this.TaxDeductionField.Equals(value) != true))
                {
                    this.TaxDeductionField = value;
                    this.RaisePropertyChanged("TaxDeduction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Year
        {
            get
            {
                return this.YearField;
            }
            set
            {
                if ((this.YearField.Equals(value) != true))
                {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRequest", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class UserRequest : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.UsernameField, value) != true))
                {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeResponse", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRDemoReportService.UserResponse))]
    public partial class EmployeeResponse : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private int EmployeeIDField;
        
        private string EmployeeNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeID
        {
            get
            {
                return this.EmployeeIDField;
            }
            set
            {
                if ((this.EmployeeIDField.Equals(value) != true))
                {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeName
        {
            get
            {
                return this.EmployeeNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.EmployeeNameField, value) != true))
                {
                    this.EmployeeNameField = value;
                    this.RaisePropertyChanged("EmployeeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserResponse", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class UserResponse : HRDemoReportService.EmployeeResponse
    {
        
        private HRDemoReportService.DepartmentResponse[] ManagedDepartmentsField;
        
        private int UserIDField;
        
        private short UserRoleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HRDemoReportService.DepartmentResponse[] ManagedDepartments
        {
            get
            {
                return this.ManagedDepartmentsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ManagedDepartmentsField, value) != true))
                {
                    this.ManagedDepartmentsField = value;
                    this.RaisePropertyChanged("ManagedDepartments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                if ((this.UserIDField.Equals(value) != true))
                {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short UserRole
        {
            get
            {
                return this.UserRoleField;
            }
            set
            {
                if ((this.UserRoleField.Equals(value) != true))
                {
                    this.UserRoleField = value;
                    this.RaisePropertyChanged("UserRole");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepartmentResponse", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class DepartmentResponse : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private int DepartmentIDField;
        
        private string DepartmentNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartmentID
        {
            get
            {
                return this.DepartmentIDField;
            }
            set
            {
                if ((this.DepartmentIDField.Equals(value) != true))
                {
                    this.DepartmentIDField = value;
                    this.RaisePropertyChanged("DepartmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentName
        {
            get
            {
                return this.DepartmentNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DepartmentNameField, value) != true))
                {
                    this.DepartmentNameField = value;
                    this.RaisePropertyChanged("DepartmentName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeRequest", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class EmployeeRequest : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private int[] ManagedDepartmentsField;
        
        private string SearchNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] ManagedDepartments
        {
            get
            {
                return this.ManagedDepartmentsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ManagedDepartmentsField, value) != true))
                {
                    this.ManagedDepartmentsField = value;
                    this.RaisePropertyChanged("ManagedDepartments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SearchName
        {
            get
            {
                return this.SearchNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchNameField, value) != true))
                {
                    this.SearchNameField = value;
                    this.RaisePropertyChanged("SearchName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HRDemoReportService.IHRDemoReportService")]
    public interface IHRDemoReportService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHRDemoReportService/GetEmployeeMonthlyReport", ReplyAction="http://tempuri.org/IHRDemoReportService/GetEmployeeMonthlyReportResponse")]
        HRDemoReportService.ReportResponse GetEmployeeMonthlyReport(HRDemoReportService.ReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHRDemoReportService/GetEmployeeMonthlyReport", ReplyAction="http://tempuri.org/IHRDemoReportService/GetEmployeeMonthlyReportResponse")]
        System.Threading.Tasks.Task<HRDemoReportService.ReportResponse> GetEmployeeMonthlyReportAsync(HRDemoReportService.ReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHRDemoReportService/GetUserDetails", ReplyAction="http://tempuri.org/IHRDemoReportService/GetUserDetailsResponse")]
        HRDemoReportService.UserResponse GetUserDetails(HRDemoReportService.UserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHRDemoReportService/GetUserDetails", ReplyAction="http://tempuri.org/IHRDemoReportService/GetUserDetailsResponse")]
        System.Threading.Tasks.Task<HRDemoReportService.UserResponse> GetUserDetailsAsync(HRDemoReportService.UserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHRDemoReportService/GetEmployeeOptions", ReplyAction="http://tempuri.org/IHRDemoReportService/GetEmployeeOptionsResponse")]
        HRDemoReportService.EmployeeResponse[] GetEmployeeOptions(HRDemoReportService.EmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHRDemoReportService/GetEmployeeOptions", ReplyAction="http://tempuri.org/IHRDemoReportService/GetEmployeeOptionsResponse")]
        System.Threading.Tasks.Task<HRDemoReportService.EmployeeResponse[]> GetEmployeeOptionsAsync(HRDemoReportService.EmployeeRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IHRDemoReportServiceChannel : HRDemoReportService.IHRDemoReportService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class HRDemoReportServiceClient : System.ServiceModel.ClientBase<HRDemoReportService.IHRDemoReportService>, HRDemoReportService.IHRDemoReportService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public HRDemoReportServiceClient() : 
                base(HRDemoReportServiceClient.GetDefaultBinding(), HRDemoReportServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IHRDemoReportService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HRDemoReportServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(HRDemoReportServiceClient.GetBindingForEndpoint(endpointConfiguration), HRDemoReportServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HRDemoReportServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(HRDemoReportServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HRDemoReportServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(HRDemoReportServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HRDemoReportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public HRDemoReportService.ReportResponse GetEmployeeMonthlyReport(HRDemoReportService.ReportRequest request)
        {
            return base.Channel.GetEmployeeMonthlyReport(request);
        }
        
        public System.Threading.Tasks.Task<HRDemoReportService.ReportResponse> GetEmployeeMonthlyReportAsync(HRDemoReportService.ReportRequest request)
        {
            return base.Channel.GetEmployeeMonthlyReportAsync(request);
        }
        
        public HRDemoReportService.UserResponse GetUserDetails(HRDemoReportService.UserRequest request)
        {
            return base.Channel.GetUserDetails(request);
        }
        
        public System.Threading.Tasks.Task<HRDemoReportService.UserResponse> GetUserDetailsAsync(HRDemoReportService.UserRequest request)
        {
            return base.Channel.GetUserDetailsAsync(request);
        }
        
        public HRDemoReportService.EmployeeResponse[] GetEmployeeOptions(HRDemoReportService.EmployeeRequest request)
        {
            return base.Channel.GetEmployeeOptions(request);
        }
        
        public System.Threading.Tasks.Task<HRDemoReportService.EmployeeResponse[]> GetEmployeeOptionsAsync(HRDemoReportService.EmployeeRequest request)
        {
            return base.Channel.GetEmployeeOptionsAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IHRDemoReportService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IHRDemoReportService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:11214/HRDemoReportService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return HRDemoReportServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IHRDemoReportService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return HRDemoReportServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IHRDemoReportService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IHRDemoReportService,
        }
    }
}
