//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRDemoAPI.Data
{
    using System;
    
    public partial class EmployeeSalary
    {
        public Nullable<double> GrossAmount { get; set; }
        public Nullable<double> PreTaxDeduction { get; set; }
        public Nullable<double> TaxDeduction { get; set; }
        public Nullable<double> PostTaxDeduction { get; set; }
        public Nullable<double> NetAmount { get; set; }
    }
}
