//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRDemoAPI.Data
{
    using System;
    
    public partial class EmployeeSalary
    {
        public double GrossAmount { get; set; }
        public double PreTaxDeduction { get; set; }
        public double TaxDeduction { get; set; }
        public double PostTaxDeduction { get; set; }
        public double NetAmount { get; set; }
    }
}
