//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRDemoAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payroll()
        {
            this.Salary = new EmployeeSalary();
        }
    
        public int PayrollID { get; set; }
        public short Month { get; set; }
        public short Year { get; set; }
        public PayrollStatus Status { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public EmployeeSalary Salary { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
